### ISSUE TITLE
Add a screen lock feature

### ISSUE THREAD

**Issue by andydotxyz** [FyshOS/fynedesk#35]

**Comment by andydotxyz** [comment]
I guess we could just use xscreensaver-command for now?

**Comment by aidan-plenert-macdonald** [comment]
For Android, need bindings to https://developer.android.com/training/sign-in/biometric-auth

**Comment by Jacalz** [comment]
> For Android, need bindings to https://developer.android.com/training/sign-in/biometric-auth

Hmm, we don’t have any other Android or mobile support at the moment as far as I know. There are most likely a lot more to do before adding screensaver support for Android.
